### ISSUE TITLE
불필요한 타입 캐스팅

### ISSUE THREAD

**Issue by vbalien** [ynifamily3/todo-app#1]
https://github.com/ynifamily3/todo-app/blob/master/src/view.ts#L10-L12

`list`, `counter`, `filters`는 `Element`타입의 필드만 사용하고 있으므로 `HTMLElement`의 캐스팅은 불필요해보입니다.

또한 `as`는 명시적 캐스팅이기 때문에 다운캐스팅 이외의 사용은 좋지 않습니다.

대신 사용해야 합니다.
`const list:HTMLElement = element.querySelector(".todo-list");`
혹은
`const list = element.querySelector<HTMLElement>(".todo-list");`

**Comment by ynifamily3** [comment]
해결했습니다 ^-^;

**Comment by ynifamily3** [comment]
https://github.com/microsoft/TypeScript/issues/283

**Comment by vbalien** [comment]
Node->Element는 다운캐스팅이잖아요
